
title: Thiago Back Adelino
url: 'https://thiagobackadelino.github.io/'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Thiago Back Adelino
tagline: Full Stack DBA DEVELOPER 
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: thiagobackadelino@gmail.com
phone: 011 97214-5989
website: blog.webjeda.com #do not add http://
linkedin: thiagobackadelino
github: thiagobackadelino
twitter: '@thiagobackadelino'

#Update all the sections by editing the files inside _includes folder.
